### ISSUE TITLE
Phar execution failure when a wrapper is used

### ISSUE THREAD

**Issue by EmanueleMinotto** [paratestphp/paratest#364]
I'm trying to run the latest paratest phar (v2.2.0) with the option `--runner=WrapperRunner` but it fails with
```
Fatal error: Uncaught TypeError: Argument 1 passed to ParaTest\Runners\PHPUnit\Worker\BaseWorker::start() must be of the type string, boolean given, called in phar:///test/bin/paratest/src/Runners/PHPUnit/WrapperRunner.php on line 60 and defined in phar:///test/bin/paratest/src/Runners/PHPUnit/Worker/BaseWorker.php:24
Stack trace:
#0 phar:///test/bin/paratest/src/Runners/PHPUnit/WrapperRunner.php(60): ParaTest\Runners\PHPUnit\Worker\BaseWorker->start(false, 1, '5c51895cdb241', Array, Object(ParaTest\Runners\PHPUnit\Options))
#1 phar:///test/bin/paratest/src/Runners/PHPUnit/WrapperRunner.php(33): ParaTest\Runners\PHPUnit\WrapperRunner->startWorkers()
#2 phar:///test/bin/paratest/src/Console/Testers/PHPUnit.php(72): ParaTest\Runners\PHPUnit\WrapperRunner->run()
#3 phar:///test/bin/paratest/src/Console/Commands/ParaTestCommand.php(73): ParaTest\Console\Testers\PHPUnit->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#4 phar:///test/bin/paratest/vendor/symfony/console/Command/Command.php(255): ParaTest\Console\Commands\ParaTestCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#5 phar:///test/bin/paratest/vendor/symfony/console/Application.php(901): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#6 phar:///test/bin/paratest/vendor/symfony/console/Application.php(262): Symfony\Component\Console\Application->doRunCommand(Object(ParaTest\Console\Commands\ParaTestCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#7 phar:///test/bin/paratest/src/Console/ParaTestApplication.php(34): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 phar:///test/bin/paratest/vendor/symfony/console/Application.php(145): ParaTest\Console\ParaTestApplication->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 phar:///test/bin/paratest/bin/paratest(34): Symfony\Component\Console\Application->run()
#10 /test/bin/paratest(10): require('phar:///test...')
#11 {main}
  thrown in phar:///test/bin/paratest/src/Runners/PHPUnit/Worker/BaseWorker.php on line 24
```

This is due to the `realpath` in https://github.com/paratestphp/paratest/blob/2.2.0/src/Runners/PHPUnit/WrapperRunner.php#L50 that doesn't work in phars.
Also a solution like `--bootstrap=vendor/autoload.php` won't solve the problem because it's used after the check on runner class existence.

Currently I have no idea of what could be a solution for this problem, anyway if something comes out I could create a PR.

**Comment by EmanueleMinotto** [comment]
ping @andreasschroth

**Comment by andreasschroth** [comment]
Sorry for late reply.

I have no spontaneous idea right now what to do about this, unfortunately. Will keep it open and hopefully come up with some solution.

**Comment by Slamdunk** [comment]
So, all in all, I don't think we would ever be able to fix this, since PHAR cannot self reference in sub-processes.

Runner only works with PHAR when you specify the phpunit binary, which is dangerous because from version 5 ParaTest is strictly coupled to the phpunit version.

I'm not going to drop the PHAR release, but I'd consider it deprecated and not supported anymore.
