### ISSUE TITLE
Exception when running paratest_for_phpstorm with --filter option 

### ISSUE THREAD

**Issue by slapoguzov** [paratestphp/paratest#695]
| Q | A
| --- | ---
| ParaTest version | 6.6.3
| PHPUnit version | 9.5.24
| PHP version | 8.1

#### Summary

When I try to run `paratest_for_phpstorm` with `--filter` option, for example:
```
/opt/homebrew/bin/php -dxdebug.mode=debug -dxdebug.client_port=9000 -dxdebug.client_host=127.0.0.1 /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/bin/paratest_for_phpstorm /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/phpunit/phpunit/phpunit --bootstrap /private/var/folders/nq/fh_373lj7p3fjqq5jvs5rg6c0000kt/T/ide-phpstorm_bootstrap.php --filter "/MyTest::testMe( .*)?$$/" /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/tests --teamcity
```

the following exception is thrown:

```
/opt/homebrew/bin/php -dxdebug.mode=debug -dxdebug.client_port=9000 -dxdebug.client_host=127.0.0.1 /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/bin/paratest_for_phpstorm /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/phpunit/phpunit/phpunit --bootstrap /private/var/folders/nq/fh_373lj7p3fjqq5jvs5rg6c0000kt/T/ide-phpstorm_bootstrap.php --filter "/MyTest::testMe( .*)?$$/" /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/tests --teamcity
Testing started at 12:12 PM ...
Testing started at 12:12 PM ...
PHP Fatal error:  Uncaught RuntimeException: Missing path to 'vendor/brianium/paratest/bin/paratest' in /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/brianium/paratest/src/Util/PhpstormHelper.php:63

Stack trace:
#0 /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/brianium/paratest/src/Util/PhpstormHelper.php(37): ParaTest\Util\PhpstormHelper::getArgvKeyFor(Array, 'vendor/brianium...')
#1 /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/brianium/paratest/bin/paratest_for_phpstorm(10): ParaTest\Util\PhpstormHelper::handleArgvFromPhpstorm(Array, '/Users/Aleksand...')
Fatal error: Uncaught RuntimeException: Missing path to 'vendor/brianium/paratest/bin/paratest' in /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/brianium/paratest/src/Util/PhpstormHelper.php:63
#2 /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/bin/paratest_for_phpstorm(120): include('/Users/Aleksand...')
Stack trace:
#3 {main}
#0 /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/brianium/paratest/src/Util/PhpstormHelper.php(37): ParaTest\Util\PhpstormHelper::getArgvKeyFor(Array, 'vendor/brianium...')
  thrown in /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/brianium/paratest/src/Util/PhpstormHelper.php on line 63
#1 /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/brianium/paratest/bin/paratest_for_phpstorm(10): ParaTest\Util\PhpstormHelper::handleArgvFromPhpstorm(Array, '/Users/Aleksand...')
#2 /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/bin/paratest_for_phpstorm(120): include('/Users/Aleksand...')
#3 {main}
  thrown in /Users/Aleksandr.Slapoguzov/PhpstormProjects/paratest_filter/vendor/brianium/paratest/src/Util/PhpstormHelper.php on line 63
```

As I know ParaTest doesn't support `--filter` option and delegates execution to `phpunit` in this case. But it seems in the case of running `paratest_for_phpstorm` it doesn't work because the PHPStorm wrapper script tries to find `paratest` binary instead of `paratest_for_phpstorm`

**Comment by steve-todorov** [comment]
I have also encountered this issue as well. The problem seems to be coming from this line (v6.6.4):

https://github.com/paratestphp/paratest/blob/4ce800dc32fd0292a4f05c00f347142dce1ecdda/src/Util/PhpstormHelper.php#L34

Debugging the code results in the following output:

```
/application/vendor/brianium/paratest/src/Util/PhpstormHelper.php:40:
array(10) {
  [0] =>  string(34) "./vendor/bin/paratest_for_phpstorm"
  [1] =>  string(24) "/application/bin/phpunit"
  [2] =>  string(15) "--configuration"
  [3] =>  string(29) "/application/phpunit.xml.dist"
  [4] =>  string(8) "--filter"
  [5] =>  string(111) "/(App\\Tests\\Services\\MyService::testSomething)( .*)?$/"
  [6] =>  string(13) "--test-suffix"
  [7] =>  string(24) "MyService.php"
  [8] =>  string(40) "/application/tests/Services/MyService"
  [9] =>  string(10) "--teamcity"
}
PHP Fatal error:  Uncaught RuntimeException: Missing path to 'vendor/brianium/paratest/bin/paratest' in /application/vendor/brianium/paratest/src/Util/PhpstormHelper.php:67
Stack trace:
#0 /application/vendor/brianium/paratest/src/Util/PhpstormHelper.php(42): ParaTest\Util\PhpstormHelper::getArgvKeyFor()
#1 /application/vendor/brianium/paratest/bin/paratest_for_phpstorm(9): ParaTest\Util\PhpstormHelper::handleArgvFromPhpstorm()
#2 /application/vendor/bin/paratest_for_phpstorm(115): include('/application/ve...')
#3 {main}
  thrown in /application/vendor/brianium/paratest/src/Util/PhpstormHelper.php on line 67
ERROR: 255

Process finished with exit code 255
```

The first argument in `$argv` is `./vendor/bin/paratest_for_phpstorm`, but the line in the code is checking for `vendor/brianium/paratest/bin/paratest`. I made myself a manual patch with the following code which solves the issue:

```diff
-        unset($argv[self::getArgvKeyFor($argv, $binPath)]);
+        $packagePath = dirname(dirname(__DIR__));
+        $binPath = $packagePath.DIRECTORY_SEPARATOR.'bin'.DIRECTORY_SEPARATOR.'paratest_for_phpstorm';
+        $binPath = "vendor/".substr($binPath, strlen($packagePath)+1);
+
+        if(realpath($binPath) == false) {
+            throw new RuntimeException("Cannot resolve absolute path to vendor/brianium/paratest/bin/paratest_for_phpstorm");
+        }
+
+        unset($argv[self::getArgvKeyFor($argv, $binPath)]);
```

I am not entirely sure if the `./vendor/bin/paratest_for_phpstorm` check shouldn't be checking for both cases.

**Comment by billypoke** [comment]
As the person who last touched the helper feature in order to make running with coverage in phpstorm work, I have a patch PR in #692 

The tests I updated should also let this case get caught if things change again in the future
