### ISSUE TITLE
Exception when using --testdox with a dataProvider 

### ISSUE THREAD

**Issue by Prokyonn** [paratestphp/paratest#738]
| Q | A
| --- | ---
| ParaTest version | 6.9.0
| PHPUnit version | 9.6.4
| PHP version | 8.0.28

#### Summary

Executing a test with a dataprovider and `--testdox` results in an error.

#### Current behavior

This exception is thrown:

```
Fatal error: Uncaught AssertionError: assert(class_exists($class)) in /Users/<user>/Development/<project>/sylius/vendor/brianium/paratest/src/Runners/PHPUnit/ResultPrinter.php:691
Stack trace:
#0 /Users/<user>/Development/<project>/sylius/vendor/brianium/paratest/src/Runners/PHPUnit/ResultPrinter.php(691): assert(false, 'assert(class_ex...')
#1 /Users/<user>/Development/<project>/sylius/vendor/brianium/paratest/src/Runners/PHPUnit/ResultPrinter.php(681): ParaTest\Runners\PHPUnit\ResultPrinter->processTestdoxReader(Object(ParaTest\Logging\JUnit\TestSuite))
#2 /Users/<user>/Development/<project>/sylius/vendor/brianium/paratest/src/Runners/PHPUnit/ResultPrinter.php(302): ParaTest\Runners\PHPUnit\ResultPrinter->processTestdoxReader(Object(ParaTest\Logging\JUnit\TestSuite))
#3 /Users/<user>/Development/<project>/sylius/vendor/brianium/paratest/src/Runners/PHPUnit/Runner.php(108): ParaTest\Runners\PHPUnit\ResultPrinter->printFeedback(Object(ParaTest\Runners\PHPUnit\Suite))
#4 /Users/<user>/Development/<project>/sylius/vendor/brianium/paratest/src/Runners/PHPUnit/Runner.php(41): ParaTest\Runners\PHPUnit\Runner->testIsStillRunning(Object(ParaTest\Runners\PHPUnit\Worker\RunnerWorker))
#5 /Users/<user>/Development/<project>/sylius/vendor/brianium/paratest/src/Runners/PHPUnit/BaseRunner.php(80): ParaTest\Runners\PHPUnit\Runner->doRun()
#6 /Users/<user>/Development/<project>/sylius/vendor/brianium/paratest/src/Console/Commands/ParaTestCommand.php(101): ParaTest\Runners\PHPUnit\BaseRunner->run()
#7 /Users/<user>/Development/<project>/sylius/vendor/symfony/console/Command/Command.php(298): ParaTest\Console\Commands\ParaTestCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /Users/<user>/Development/<project>/sylius/vendor/symfony/console/Application.php(1040): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /Users/<user>/Development/<project>/sylius/vendor/symfony/console/Application.php(301): Symfony\Component\Console\Application->doRunCommand(Object(ParaTest\Console\Commands\ParaTestCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /Users/<user>/Development/<project>/sylius/vendor/symfony/console/Application.php(171): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /Users/<user>/Development/<project>/sylius/vendor/brianium/paratest/bin/paratest(37): Symfony\Component\Console\Application->run()
```

#### How to reproduce: command, code and error stack trace

Create a test with a dataproveder e.g.
```php
use PHPUnit\Framework\TestCase;

class ExampleTest extends TestCase
{
    /**
     * @dataProvider provideTrimData
     */
    public function testTrim($expectedResult, $input): void
    {
        self::assertSame($expectedResult, trim($input));
    }

    public function provideTrimData()
    {
        return [
            'leading space is trimmed' => [
                'Hello World',
                ' Hello World',
            ],
            'trailing space and newline are trimmed' => [
                'Hello World',
                "Hello World \n",
            ],
        ];
    }
}
```

and run it with paratest and testdox:

`php vendor/bin/paratest --testdox ./tests/ExampleTest.php`

#### Expected behavior

Test doesn't throw an exception and works the same as with phpunit or without testdox

**Comment by Slamdunk** [comment]
Fix released, thank you for reporting this
