### ISSUE TITLE
EventFacadeIsSealedException with PHPUnit 11.5

### ISSUE THREAD

**Issue by InvisibleSmiley** [paratestphp/paratest#915]
| Q | A
| --- | ---
| ParaTest version | 7.6.1
| PHPUnit version | 11.5.0
| PHP version | 8.3.14

#### Summary

Execution fails due to EventFacadeIsSealedException

#### Current behavior

Execution fails

#### How to reproduce: command, code and error stack trace

```
ParaTest v7.6.1 upon PHPUnit 11.5.0 by Sebastian Bergmann and contributors.

Processes:     10
Runtime:       PHP 8.3.14
Configuration: /path/to/my/project/phpunit.xml.dist


In WorkerCrashedException.php line 41:

  The test "PARATEST='1' TEST_TOKEN='2' UNIQUE_TEST_TOKEN='2_6752a562f1437' path/to/my/Test.php" failed.

  Exit Code: 255(Unknown error)

  Working directory: /path/to/my/project

  Output:
  ================

  Fatal error: Uncaught PHPUnit\Event\EventFacadeIsSealedException in /path/to/my/project/vendor/phpunit/phpunit/src/Event/Facade.php on line 70

  PHPUnit\Event\EventFacadeIsSealedException:  in /path/to/my/project/vendor/phpunit/phpunit/src/Event/Facade.php on line 70

  Call Stack:
      0.0001     714672   1. {main}() /path/to/my/project/vendor/brianium/paratest/bin/phpunit-wrapper.php:0
      0.0001     715088   2. {closure:/path/to/my/project/vendor/brianium/paratest/bin/phpunit-wrapper.php:8-82}() /path/to/my/project/vendor/brianium/paratest/bin/phpunit-wrapper.php:82
      0.0246    5167592   3. ParaTest\WrapperRunner\ApplicationForWrapperWorker->runTest($testPath = 'path/to/my/Test.php') /path/to/my/project/vendor/br
  ianium/paratest/bin/phpunit-wrapper.php:77
      0.0769   10173488   4. PHPUnit\Framework\TestSuite->run() /path/to/my/project/vendor/brianium/paratest/src/WrapperRunner/ApplicationForWrapperWorker.php:123
      0.0787   10240768   5. PHPUnit\TestRunner\TestResult\Facade::shouldStop() /path/to/my/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php:363
      0.0787   10240768   6. PHPUnit\TestRunner\TestResult\Facade::stopOnDeprecation($configuration = class PHPUnit\TextUI\Configuration\Configuration { private readonly array $cliArguments = []; private readonly ?string $configurationFile = '/path/to
  my/project/phpunit.xml.dist'; private readonly ?string $bootstrap = '/path/to/my/project/vendor/autoload.php'; private readonly bool $cacheResult = FALSE; private readonly ?string $cacheDirector
  y = '/path/to/my/project/data/phpunit'; private readonly ?string $coverageCacheDirectory = '/path/to/my/project/data/phpunit/code-coverage'; private readonly PHPUnit\TextUI\Configuration\Source $
  source = class PHPUnit\TextUI\Configuration\Source { private readonly ?string $baseline = NULL; private readonly bool $ignoreBaseline = FALSE; private readonly PHPUnit\TextUI\Configuration\FilterDirectoryCollection $includeDirectories = class PHPUni
  t\TextUI\Configuration\FilterDirectoryCollection { ... }; private readonly PHPUnit\TextUI\Configuration\FileCollection $includeFiles = class PHPUnit\TextUI\Configuration\FileCollection { ... }; private readonly PHPUnit\TextUI\Configuration\FilterDir
  ectoryCollection $excludeDirectories = class PHPUnit\TextUI\Configuration\FilterDirectoryCollection { ... }; private readonly PHPUnit\TextUI\Configuration\FileCollection $excludeFiles = class PHPUnit\TextUI\Configuration\FileCollection { ... }; priv
  ate readonly bool $restrictDeprecations = FALSE; private readonly bool $restrictNotices = FALSE; private readonly bool $restrictWarnings = FALSE; private readonly bool $ignoreSuppressionOfDeprecations = FALSE; private readonly bool $ignoreSuppressio
  nOfPhpDeprecations = FALSE; private readonly bool $ignoreSuppressionOfErrors = FALSE; private readonly bool $ignoreSuppressionOfNotices = FALSE; private readonly bool $ignoreSuppressionOfPhpNotices = FALSE; private readonly bool $ignoreSuppressionOf
  Warnings = FALSE; private readonly bool $ignoreSuppressionOfPhpWarnings = FALSE; private readonly bool $ignoreSelfDeprecations = FALSE; private readonly bool $ignoreDirectDeprecations = FALSE; private readonly bool $ignoreIndirectDeprecations = FALS
  E; private readonly array $deprecationTriggers = [...] }; private readonly bool $pathCoverage = FALSE; private readonly ?string $coverageClover = NULL; private readonly ?string $coverageCobertura = NULL; private readonly ?string $coverageCrap4j = NU
  LL; private readonly int $coverageCrap4jThreshold = 30; private readonly ?string $coverageHtml = NULL; private readonly int $coverageHtmlLowUpperBound = 50; private readonly int $coverageHtmlHighLowerBound = 90; private readonly string $coverageHtml
  ColorSuccessLow = '#dff0d8'; private readonly string $coverageHtmlColorSuccessMedium = '#c3e3b5'; private readonly string $coverageHtmlColorSuccessHigh = '#99cb84'; private readonly string $coverageHtmlColorWarning = '#fcf8e3'; private readonly stri
  ng $coverageHtmlColorDanger = '#f2dede'; private readonly ?string $coverageHtmlCustomCssFile = NULL; private readonly ?string $coveragePhp = NULL; private readonly ?string $coverageText = NULL; private readonly bool $coverageTextShowUncoveredFiles =
   FALSE; private readonly bool $coverageTextShowOnlySummary = FALSE; private readonly ?string $coverageXml = NULL; private readonly string $testResultCacheFile = '/path/to/my/project/data/phpunit/test-results'; private read
  only bool $ignoreDeprecatedCodeUnitsFromCodeCoverage = FALSE; private readonly bool $disableCodeCoverageIgnore = FALSE; private readonly bool $failOnDeprecation = TRUE; private readonly bool $failOnPhpunitDeprecation = FALSE; private readonly bool $
  failOnEmptyTestSuite = FALSE; private readonly bool $failOnIncomplete = FALSE; private readonly bool $failOnNotice = FALSE; private readonly bool $failOnRisky = TRUE; private readonly bool $failOnSkipped = FALSE; private readonly bool $failOnWarning
   = TRUE; private readonly bool $stopOnDefect = FALSE; private readonly bool $stopOnDeprecation = TRUE; private readonly ?string $specificDeprecationToStopOn = NULL; private readonly bool $stopOnError = FALSE; private readonly bool $stopOnFailure = F
  ALSE; private readonly bool $stopOnIncomplete = FALSE; private readonly bool $stopOnNotice = FALSE; private readonly bool $stopOnRisky = TRUE; private readonly bool $stopOnSkipped = FALSE; private readonly bool $stopOnWarning = TRUE; private readonl
  y bool $outputToStandardErrorStream = FALSE; private readonly int $columns = 80; private readonly bool $noExtensions = FALSE; private readonly ?string $pharExtensionDirectory = NULL; private readonly array $extensionBootstrappers = []; private reado
  nly bool $backupGlobals = FALSE; private readonly bool $backupStaticProperties = FALSE; private readonly bool $beStrictAboutChangesToGlobalState = FALSE; private readonly bool $colors = FALSE; private readonly bool $processIsolation = FALSE; private
   readonly bool $enforceTimeLimit = FALSE; private readonly int $defaultTimeLimit = 1; private readonly int $timeoutForSmallTests = 1; private readonly int $timeoutForMediumTests = 10; private readonly int $timeoutForLargeTests = 60; private readonly
   bool $reportUselessTests = TRUE; private readonly bool $strictCoverage = TRUE; private readonly bool $disallowTestOutput = TRUE; private readonly bool $displayDetailsOnIncompleteTests = TRUE; private readonly bool $displayDetailsOnSkippedTests = TR
  UE; private readonly bool $displayDetailsOnTestsThatTriggerDeprecations = TRUE; private readonly bool $displayDetailsOnPhpunitDeprecations = TRUE; private readonly bool $displayDetailsOnTestsThatTriggerErrors = TRUE; private readonly bool $displayDe
  tailsOnTestsThatTriggerNotices = TRUE; private readonly bool $displayDetailsOnTestsThatTriggerWarnings = TRUE; private readonly bool $reverseDefectList = FALSE; private readonly bool $requireCoverageMetadata = TRUE; private readonly bool $noProgress
   = FALSE; private readonly bool $noResults = FALSE; private readonly bool $noOutput = TRUE; private readonly int $executionOrder = 0; private readonly int $executionOrderDefects = 3; private readonly bool $resolveDependencies = TRUE; private readonl
  y ?string $logfileTeamcity = NULL; private readonly ?string $logfileJunit = NULL; private readonly ?string $logfileTestdoxHtml = NULL; private readonly ?string $logfileTestdoxText = NULL; private readonly ?string $logEventsText = NULL; private reado
  nly ?string $logEventsVerboseText = NULL; private readonly ?array $testsCovering = NULL; private readonly ?array $testsUsing = NULL; private readonly ?array $testsRequiringPhpExtension = NULL; private readonly bool $teamCityOutput = FALSE; private r
  eadonly bool $testDoxOutput = FALSE; private readonly bool $testDoxOutputSummary = FALSE; private readonly ?string $filter = NULL; private readonly ?string $excludeFilter = NULL; private readonly array $groups = []; private readonly array $excludeGr
  oups = []; private readonly int $randomOrderSeed = 1733469539; private readonly bool $includeUncoveredFiles = TRUE; private readonly PHPUnit\TextUI\Configuration\TestSuiteCollection $testSuite = class PHPUnit\TextUI\Configuration\TestSuiteCollection
   { private readonly array $testSuites = [...] }; private readonly string $includeTestSuite = ''; private readonly string $excludeTestSuite = ''; private readonly ?string $defaultTestSuite = NULL; private readonly array $testSuffixes = [0 => 'Test.ph
  p', 1 => '.phpt']; private readonly PHPUnit\TextUI\Configuration\Php $php = class PHPUnit\TextUI\Configuration\Php { private readonly PHPUnit\TextUI\Configuration\DirectoryCollection $includePaths = class PHPUnit\TextUI\Configuration\DirectoryCollec
  tion { ... }; private readonly PHPUnit\TextUI\Configuration\IniSettingCollection $iniSettings = class PHPUnit\TextUI\Configuration\IniSettingCollection { ... }; private readonly PHPUnit\TextUI\Configuration\ConstantCollection $constants = class PHPU
  nit\TextUI\Configuration\ConstantCollection { ... }; private readonly PHPUnit\TextUI\Configuration\VariableCollection $globalVariables = class PHPUnit\TextUI\Configuration\VariableCollection { ... }; private readonly PHPUnit\TextUI\Configuration\Var
  iableCollection $envVariables = class PHPUnit\TextUI\Configuration\VariableCollection { ... }; private readonly PHPUnit\TextUI\Configuration\VariableCollection $postVariables = class PHPUnit\TextUI\Configuration\VariableCollection { ... }; private r
  eadonly PHPUnit\TextUI\Configuration\VariableCollection $getVariables = class PHPUnit\TextUI\Configuration\VariableCollection { ... }; private readonly PHPUnit\TextUI\Configuration\VariableCollection $cookieVariables = class PHPUnit\TextUI\Configura
  tion\VariableCollection { ... }; private readonly PHPUnit\TextUI\Configuration\VariableCollection $serverVariables = class PHPUnit\TextUI\Configuration\VariableCollection { ... }; private readonly PHPUnit\TextUI\Configuration\VariableCollection $fil
  esVariables = class PHPUnit\TextUI\Configuration\VariableCollection { ... }; private readonly PHPUnit\TextUI\Configuration\VariableCollection $requestVariables = class PHPUnit\TextUI\Configuration\VariableCollection { ... } }; private readonly bool
  $controlGarbageCollector = FALSE; private readonly int $numberOfTestsBeforeGarbageCollection = 100; private readonly ?string $generateBaseline = NULL; private readonly bool $debug = FALSE; private readonly int $shortenArraysForExportThreshold = 0 })
   /path/to/my/project/vendor/phpunit/phpunit/src/Runner/TestResult/Facade.php:73
      0.0788   10244240   7. PHPUnit\Runner\DeprecationCollector\Facade::deprecations() /path/to/my/project/vendor/phpunit/phpunit/src/Runner/TestResult/Facade.php:116
      0.0788   10244240   8. PHPUnit\Runner\DeprecationCollector\Facade::collector() /path/to/my/project/vendor/phpunit/phpunit/src/Runner/DeprecationCollector/Facade.php:42
      0.0789   10248096   9. PHPUnit\Runner\DeprecationCollector\Collector->__construct($facade = class PHPUnit\Event\Facade { private PHPUnit\Event\Emitter $emitter = class PHPUnit\Event\DispatchingEmitter { private readonly PHPUnit\Event\Dispatcher
  $dispatcher = class PHPUnit\Event\DeferringDispatcher { ... }; private readonly PHPUnit\Event\Telemetry\System $system = class PHPUnit\Event\Telemetry\System { ... }; private readonly PHPUnit\Event\Telemetry\Snapshot $startSnapshot = class PHPUnit\E
  vent\Telemetry\Snapshot { ... }; private PHPUnit\Event\Telemetry\Snapshot $previousSnapshot = class PHPUnit\Event\Telemetry\Snapshot { ... } }; private ?PHPUnit\Event\TypeMap $typeMap = class PHPUnit\Event\TypeMap { private array $mapping = [...] };
   private ?PHPUnit\Event\DeferringDispatcher $deferringDispatcher = class PHPUnit\Event\DeferringDispatcher { private readonly PHPUnit\Event\SubscribableDispatcher $dispatcher = class PHPUnit\Event\DirectDispatcher { ... }; private PHPUnit\Event\Even
  tCollection $events = class PHPUnit\Event\EventCollection { ... }; private bool $recording = FALSE }; private bool $sealed = TRUE }) /path/to/my/project/vendor/phpunit/phpunit/src/Runner/DeprecationCollector/Facade.php:52
      0.0790   10253944  10. PHPUnit\Event\Facade->registerSubscribers(...$subscribers = variadic(class PHPUnit\Runner\DeprecationCollector\TestPreparedSubscriber { private readonly PHPUnit\Runner\DeprecationCollector\Collector ${PHPUnit\Runner\Deprec
  ationCollector\Subscriber}collector = class PHPUnit\Runner\DeprecationCollector\Collector { private array $deprecations = [...] } }, class PHPUnit\Runner\DeprecationCollector\TestTriggeredDeprecationSubscriber { private readonly PHPUnit\Runner\Depre
  cationCollector\Collector ${PHPUnit\Runner\DeprecationCollector\Subscriber}collector = class PHPUnit\Runner\DeprecationCollector\Collector { private array $deprecations = [...] } })) /path/to/my/project/vendor/phpunit/phpu
  nit/src/Runner/DeprecationCollector/Collector.php:35
      0.0790   10254160  11. PHPUnit\Event\Facade->registerSubscriber($subscriber = class PHPUnit\Runner\DeprecationCollector\TestPreparedSubscriber { private readonly PHPUnit\Runner\DeprecationCollector\Collector ${PHPUnit\Runner\DeprecationCollector
  \Subscriber}collector = class PHPUnit\Runner\DeprecationCollector\Collector { private array $deprecations = [...] } }) /path/to/my/project/vendor/phpunit/phpunit/src/Event/Facade.php:59



  Error Output:
  ================
  PHP Fatal error:  Uncaught PHPUnit\Event\EventFacadeIsSealedException in /path/to/my/project/vendor/phpunit/phpunit/src/Event/Facade.php:70
  Stack trace:
  #0 /path/to/my/project/vendor/phpunit/phpunit/src/Event/Facade.php(59): PHPUnit\Event\Facade->registerSubscriber(Object(PHPUnit\Runner\DeprecationCollector\TestPreparedSubscriber))
  #1 /path/to/my/project/vendor/phpunit/phpunit/src/Runner/DeprecationCollector/Collector.php(35): PHPUnit\Event\Facade->registerSubscribers(Object(PHPUnit\Runner\DeprecationCollector\TestPreparedSubscriber), Object(PHPUnit\
  Runner\DeprecationCollector\TestTriggeredDeprecationSubscriber))
  #2 /path/to/my/project/vendor/phpunit/phpunit/src/Runner/DeprecationCollector/Facade.php(52): PHPUnit\Runner\DeprecationCollector\Collector->__construct(Object(PHPUnit\Event\Facade))
  #3 /path/to/my/project/vendor/phpunit/phpunit/src/Runner/DeprecationCollector/Facade.php(42): PHPUnit\Runner\DeprecationCollector\Facade::collector()
  #4 /path/to/my/project/vendor/phpunit/phpunit/src/Runner/TestResult/Facade.php(116): PHPUnit\Runner\DeprecationCollector\Facade::deprecations()
  #5 /path/to/my/project/vendor/phpunit/phpunit/src/Runner/TestResult/Facade.php(73): PHPUnit\TestRunner\TestResult\Facade::stopOnDeprecation(Object(PHPUnit\TextUI\Configuration\Configuration))
  #6 /path/to/my/project/vendor/phpunit/phpunit/src/Framework/TestSuite.php(363): PHPUnit\TestRunner\TestResult\Facade::shouldStop()
  #7 /path/to/my/project/vendor/brianium/paratest/src/WrapperRunner/ApplicationForWrapperWorker.php(123): PHPUnit\Framework\TestSuite->run()
  #8 /path/to/my/project/vendor/brianium/paratest/bin/phpunit-wrapper.php(77): ParaTest\WrapperRunner\ApplicationForWrapperWorker->runTest('path/to/...')
  #9 /path/to/my/project/vendor/brianium/paratest/bin/phpunit-wrapper.php(82): {closure}()
  #10 {main}
    thrown in /path/to/my/project/vendor/phpunit/phpunit/src/Event/Facade.php on line 70
```

#### Expected behavior

No errors (as with PHPUnit < 11.5.0)

**Comment by Slamdunk** [comment]
Please provide a reproducible environment where the error happens, otherwise we can't do much

**Comment by InvisibleSmiley** [comment]
Reproducible for me when running `vendor/bin/paratest test` with:

phpunit.xml.dist
```
<phpunit stopOnDeprecation="true"/>
```

composer.json
```
{
    "require": {
        "php": "^8.3"
    },
    "require-dev": {
        "brianium/paratest": "^7.0",
        "phpunit/phpunit": "^11.5"
    },
    "autoload-dev": {
        "psr-4": {
            "Foo\\Test\\": "test"
        }
    }
}
```

test/FooTest.php
```
<?php

declare(strict_types=1);

namespace Foo\Test;

use PHPUnit\Framework\TestCase;

class FooTest extends TestCase
{
    public function test(): void
    {
        self::assertSame(1,1);
    }
}
```

**Comment by InvisibleSmiley** [comment]
In case it matters, I'm on macOS Sonoma 14.7.1.

**Comment by InvisibleSmiley** [comment]
Verified, thanks!
